### PR TITLE
Button groups and cards updated

### PR DESCRIPTION
**Pull request by claudsonm**
The folders `cards` and `button_group` has been updated.

### CODE REVIEW

**Comment by 1337domz** [comment]
Came here to mention that card-block doesn't seem to exist in Bootstrap 4 and it's called card-body, but looks like this pull request fixes that.

**Comment by niladam** [comment]
@degouville -- what's wrong with this PR ?

**Comment by niladam** [comment]
Congrats @claudsonm !:) And thank you @degouville !:)

**Comment by niladam** [comment]
@claudsonm can you please update the README to reflect the changes that you're provided ? Also, maybe document the ones that are missing ?

**Comment by degouville** [comment]
@niladam Can you please help me on this one before so i can launch next release ?

Fork + Update + PR = ❤️

**Comment by niladam** [comment]
@degouville i'd be happy to. Sadly, i'd need to fully test them and i can't do it right now. However, i'll be able to provide a helping hand sometimes next week. 

I was merely checking this and was happy to find it. I think it's a great addition and i also think a lot of things could be improved :)

**Pull request merged**
